BASE_DIR = "/path/to/project"
CHROME_DRIVER_PATH = ""
CHROME_BINARY_PATH = ""
OPTIPNG_PATH = "tools/optimizers/optipng.exe"
CWEBP_PATH = "tools/optimizers/cwebp.exe"
SUFFIX_FILE_PATH = "/path/to/project/custom_suffixes.py"
LINKS_FILE_PATH = "/path/to/project/liens_clean.txt"
ROOT_FOLDER = "image"
THEME = "dark"
WP_DOMAIN = "https://monsite.com"
WP_UPLOAD_PATH = "wp-content/uploads/2025/06"
IMAGE_NAME_PATTERN = "{id}:{variant}-{name}.webp"
